# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd334a38c2a48cb65eeea28e6ded4087bc9310ceb19eb7ba23c63ebbfe8d87885cc9f23977c015371776235038cbdf5c3f7376d86512aa5fe65c7919abe3d281

test:
  secret_key_base: eacfc83d9e155c670cbc359d958c045b2b6eccd23688c76959c331231cc773d41db30f4c59e85e27ed8406375b899a8ff918a60d044949fbd056192ebd687c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
